#!/bin/bash

openssl genrsa -out server.key 2048
openssl rsa -in server.key -out server.key
openssl req -sha256 -new -key server.key -out server.csr \
    -subj "/CN=moroz.local" \
    -addext "subjectAltName = DNS:moroz.local" 
openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt -copy_extensions=copyall
rm -f server.csr
